version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9144
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "9001:9001"